### PR TITLE
Refactorize the CLI code - extended

### PR DESCRIPTION
**Pull request by jonludlam**
This is mostly @Drup's work from PR #455 with some backwards compatibility (sufficient to ensure odig works at least once) and some extra work to support the three step process (compile/link/generate).

I expect to revisit this when a decision on the work on parent/child relationships is finalised, but it's helpful to have it in now to support the work on the reference driver and the new test suite.

### CODE REVIEW

**Review by Julow — APPROVED** [review]
The code looks good. Of course, this breaks `odig` and `dune`.

Here the diff of the `--help` generated by cmdliner for every commands:

<details>
<summary>(very long)</summary>

```diff
diff --git a/7e488de4/odoc b/d0fda807/odoc
index 47e1bebd..4befca32 100644
--- a/7e488de4/odoc
+++ b/d0fda807/odoc
@@ -19,29 +19,44 @@ COMMANDS
        css DEPRECATED: Use `odoc support-files' to copy the CSS file for the
            default theme.
 
-       generate
-           Generates an html file from an odocl one
-
        html
-           Generates an html file from an odoc one
+           Render html files from an odoc one
 
        html-deps
-           lists the packages which need to be in odoc's load path to process
-           html from the .odoc files in the given directory
+           DEPRECATED: alias for render-deps
 
        html-fragment
            Generates an html fragment file from an mld one
 
+       html-generate
+           Generate html files from an odocl one
+
        html-targets
            TODO: Fill in.
 
        latex
-           Generates a latex file from an odoc one
+           Render latex files from an odoc one
+
+       latex-generate
+           Generate latex files from an odocl one
+
+       latex-targets
+           TODO: Fill in.
 
        link
            Link odoc files together
 
-       man Generates a man page file from an odoc one
+       link-deps
+           lists the packages which need to be in odoc's load path to link
+           the .odoc files in the given directory
+
+       man Render man files from an odoc one
+
+       man-generate
+           Generate man files from an odocl one
+
+       man-targets
+           TODO: Fill in.
 
        support-files
            Copy the support files (e.g. default theme, JavaScript files) to
diff --git a/7e488de4/odoc html b/d0fda807/odoc html
index fe57255e..af445f54 100644
--- a/7e488de4/odoc html	
+++ b/d0fda807/odoc html	
@@ -1,5 +1,5 @@
 NAME
-       odoc-html - Generates an html file from an odoc one
+       odoc-html - Render html files from an odoc one
 
 SYNOPSIS
        odoc html [OPTION]... file.odoc
@@ -16,9 +16,6 @@ ARGUMENTS
        -o DIR, --output-dir=DIR (required)
            Output directory where the HTML tree is expected to be saved.
 
-       --warn-error (absent ODOC_WARN_ERROR env)
-           Turn warnings into errors.
-
        file.odoc (required)
            Input file
 
@@ -32,13 +29,6 @@ OPTIONS
            `pager', `groff' or `plain'. With `auto', the format is `pager` or
            `plain' whenever the TERM env var is `dumb' or undefined.
 
-       --index-for=PKG
-           DEPRECATED: you should use 'odoc compile' to process .mld files.
-           When this argument is given, then the input file is expected to be
-           a .mld file. The output will be a "index.html" file in the output
-           directory. PKG is using to correctly resolve and link references
-           inside the input file
-
        --semantic-uris, --pretty-uris
            Generate pretty (semantic) links
 
@@ -58,6 +48,3 @@ ENVIRONMENT
        ODOC_SYNTAX
            See option --syntax.
 
-       ODOC_WARN_ERROR
-           Turn warnings into errors. See option --warn-error.
-
diff --git a/7e488de4/odoc html-deps b/d0fda807/odoc html-deps
index ac6a0900..92b5a995 100644
--- a/7e488de4/odoc html-deps	
+++ b/d0fda807/odoc html-deps	
@@ -1,11 +1,13 @@
 NAME
-       odoc-html-deps - lists the packages which need to be in odoc's load
-       path to process html from the .odoc files in the given directory
+       odoc-html-deps - DEPRECATED: alias for render-deps
 
 SYNOPSIS
        odoc html-deps [OPTION]... PKG_DIR
 
 ARGUMENTS
+       -I DIR
+           For backwards compatibility. Ignored.
+
        PKG_DIR (required)
            Input directory
 
diff --git a/7e488de4/odoc generate b/d0fda807/odoc html-generate
similarity index 73%
rename from 7e488de4/odoc generate
rename to d0fda807/odoc html-generate
index 859f1f72..0a11b50b 100644
--- a/7e488de4/odoc generate	
+++ b/d0fda807/odoc html-generate	
@@ -1,17 +1,18 @@
 NAME
-       odoc-generate - Generates an html file from an odocl one
+       odoc-html-generate - Generate html files from an odocl one
 
 SYNOPSIS
-       odoc generate [OPTION]... file.odocl
+       odoc html-generate [OPTION]... file.odoc
 
 ARGUMENTS
+       --hidden
+           Mark the unit as hidden. (Useful for files included in module
+           packs).
+
        -o DIR, --output-dir=DIR (required)
            Output directory where the HTML tree is expected to be saved.
 
-       --warn-error (absent ODOC_WARN_ERROR env)
-           Turn warnings into errors.
-
-       file.odocl (required)
+       file.odoc (required)
            Input file
 
 OPTIONS
@@ -38,11 +39,8 @@ OPTIONS
            Show version information.
 
 ENVIRONMENT
-       These environment variables affect the execution of generate:
+       These environment variables affect the execution of html-generate:
 
        ODOC_SYNTAX
            See option --syntax.
 
-       ODOC_WARN_ERROR
-           Turn warnings into errors. See option --warn-error.
-
diff --git a/7e488de4/odoc html-targets b/d0fda807/odoc html-targets
index 6e922545..a3ae0288 100644
--- a/7e488de4/odoc html-targets	
+++ b/d0fda807/odoc html-targets	
@@ -6,8 +6,7 @@ SYNOPSIS
 
 ARGUMENTS
        -I DIR
-           Where to look for required .odoc files. (Can be present several
-           times).
+           For backwards compatibility. Ignored.
 
        -o DIR, --output-dir=DIR (required)
            Output directory where the HTML tree is expected to be saved.
@@ -16,11 +15,22 @@ ARGUMENTS
            Input file
 
 OPTIONS
+       --closed-details
+           If this flag is passed <details> tags (used for includes) will be
+           closed by default.
+
        --help[=FMT] (default=auto)
            Show this help in format FMT. The value FMT must be one of `auto',
            `pager', `groff' or `plain'. With `auto', the format is `pager` or
            `plain' whenever the TERM env var is `dumb' or undefined.
 
+       --semantic-uris, --pretty-uris
+           Generate pretty (semantic) links
+
+       --theme-uri=URI (absent=./)
+           Where to look for theme files (e.g. `URI/odoc.css'). Relative URIs
+           are resolved using `--output-dir' as a target.
+
        --version
            Show version information.
 
diff --git a/7e488de4/odoc latex b/d0fda807/odoc latex
index 372d939c..db28cec4 100644
--- a/7e488de4/odoc latex	
+++ b/d0fda807/odoc latex	
@@ -1,10 +1,14 @@
 NAME
-       odoc-latex - Generates a latex file from an odoc one
+       odoc-latex - Render latex files from an odoc one
 
 SYNOPSIS
        odoc latex [OPTION]... file.odoc
 
 ARGUMENTS
+       --hidden
+           Mark the unit as hidden. (Useful for files included in module
+           packs).
+
        -I DIR
            Where to look for required .odoc files. (Can be present several
            times).
diff --git a/d0fda807/odoc latex-generate b/d0fda807/odoc latex-generate
new file mode 100644
index 00000000..2568c8ea
--- /dev/null
+++ b/d0fda807/odoc latex-generate	
@@ -0,0 +1,38 @@
+NAME
+       odoc-latex-generate - Generate latex files from an odocl one
+
+SYNOPSIS
+       odoc latex-generate [OPTION]... file.odoc
+
+ARGUMENTS
+       --hidden
+           Mark the unit as hidden. (Useful for files included in module
+           packs).
+
+       -o DIR, --output-dir=DIR (required)
+           Output directory where the HTML tree is expected to be saved.
+
+       file.odoc (required)
+           Input file
+
+OPTIONS
+       --help[=FMT] (default=auto)
+           Show this help in format FMT. The value FMT must be one of `auto',
+           `pager', `groff' or `plain'. With `auto', the format is `pager` or
+           `plain' whenever the TERM env var is `dumb' or undefined.
+
+       --syntax=SYNTAX (absent=ml or ODOC_SYNTAX env)
+           Available options: ml | re
+
+       --version
+           Show version information.
+
+       --with-children=BOOL (absent=true)
+           Include children at the end of the page
+
+ENVIRONMENT
+       These environment variables affect the execution of latex-generate:
+
+       ODOC_SYNTAX
+           See option --syntax.
+
diff --git a/d0fda807/odoc latex-targets b/d0fda807/odoc latex-targets
new file mode 100644
index 00000000..5b60d5c7
--- /dev/null
+++ b/d0fda807/odoc latex-targets	
@@ -0,0 +1,28 @@
+NAME
+       odoc-latex-targets - TODO: Fill in.
+
+SYNOPSIS
+       odoc latex-targets [OPTION]... file.odoc
+
+ARGUMENTS
+       -I DIR
+           For backwards compatibility. Ignored.
+
+       -o DIR, --output-dir=DIR (required)
+           Output directory where the HTML tree is expected to be saved.
+
+       file.odoc (required)
+           Input file
+
+OPTIONS
+       --help[=FMT] (default=auto)
+           Show this help in format FMT. The value FMT must be one of `auto',
+           `pager', `groff' or `plain'. With `auto', the format is `pager` or
+           `plain' whenever the TERM env var is `dumb' or undefined.
+
+       --version
+           Show version information.
+
+       --with-children=BOOL (absent=true)
+           Include children at the end of the page
+
diff --git a/7e488de4/odoc link b/d0fda807/odoc link
index 3f2bec24..5d08d929 100644
--- a/7e488de4/odoc link	
+++ b/d0fda807/odoc link	
@@ -9,6 +9,11 @@ ARGUMENTS
            Where to look for required .odoc files. (Can be present several
            times).
 
+       -o PATH
+           Output file path. Non-existing intermediate directories are
+           created. If absent outputs a .odocl file in the same directory as
+           the input file.
+
        --warn-error (absent ODOC_WARN_ERROR env)
            Turn warnings into errors.
 
diff --git a/d0fda807/odoc link-deps b/d0fda807/odoc link-deps
new file mode 100644
index 00000000..d51ec7f3
--- /dev/null
+++ b/d0fda807/odoc link-deps	
@@ -0,0 +1,20 @@
+NAME
+       odoc-link-deps - lists the packages which need to be in odoc's load
+       path to link the .odoc files in the given directory
+
+SYNOPSIS
+       odoc link-deps [OPTION]... PKG_DIR
+
+ARGUMENTS
+       PKG_DIR (required)
+           Input directory
+
+OPTIONS
+       --help[=FMT] (default=auto)
+           Show this help in format FMT. The value FMT must be one of `auto',
+           `pager', `groff' or `plain'. With `auto', the format is `pager` or
+           `plain' whenever the TERM env var is `dumb' or undefined.
+
+       --version
+           Show version information.
+
diff --git a/7e488de4/odoc man b/d0fda807/odoc man
index 173a7d5f..0052182c 100644
--- a/7e488de4/odoc man	
+++ b/d0fda807/odoc man	
@@ -1,10 +1,14 @@
 NAME
-       odoc-man - Generates a man page file from an odoc one
+       odoc-man - Render man files from an odoc one
 
 SYNOPSIS
        odoc man [OPTION]... file.odoc
 
 ARGUMENTS
+       --hidden
+           Mark the unit as hidden. (Useful for files included in module
+           packs).
+
        -I DIR
            Where to look for required .odoc files. (Can be present several
            times).
diff --git a/d0fda807/odoc man-generate b/d0fda807/odoc man-generate
new file mode 100644
index 00000000..8a3c99ec
--- /dev/null
+++ b/d0fda807/odoc man-generate	
@@ -0,0 +1,35 @@
+NAME
+       odoc-man-generate - Generate man files from an odocl one
+
+SYNOPSIS
+       odoc man-generate [OPTION]... file.odoc
+
+ARGUMENTS
+       --hidden
+           Mark the unit as hidden. (Useful for files included in module
+           packs).
+
+       -o DIR, --output-dir=DIR (required)
+           Output directory where the HTML tree is expected to be saved.
+
+       file.odoc (required)
+           Input file
+
+OPTIONS
+       --help[=FMT] (default=auto)
+           Show this help in format FMT. The value FMT must be one of `auto',
+           `pager', `groff' or `plain'. With `auto', the format is `pager` or
+           `plain' whenever the TERM env var is `dumb' or undefined.
+
+       --syntax=SYNTAX (absent=ml or ODOC_SYNTAX env)
+           Available options: ml | re
+
+       --version
+           Show version information.
+
+ENVIRONMENT
+       These environment variables affect the execution of man-generate:
+
+       ODOC_SYNTAX
+           See option --syntax.
+
diff --git a/d0fda807/odoc man-targets b/d0fda807/odoc man-targets
new file mode 100644
index 00000000..c4d267fc
--- /dev/null
+++ b/d0fda807/odoc man-targets	
@@ -0,0 +1,25 @@
+NAME
+       odoc-man-targets - TODO: Fill in.
+
+SYNOPSIS
+       odoc man-targets [OPTION]... file.odoc
+
+ARGUMENTS
+       -I DIR
+           For backwards compatibility. Ignored.
+
+       -o DIR, --output-dir=DIR (required)
+           Output directory where the HTML tree is expected to be saved.
+
+       file.odoc (required)
+           Input file
+
+OPTIONS
+       --help[=FMT] (default=auto)
+           Show this help in format FMT. The value FMT must be one of `auto',
+           `pager', `groff' or `plain'. With `auto', the format is `pager` or
+           `plain' whenever the TERM env var is `dumb' or undefined.
+
+       --version
+           Show version information.
+
```

</details>

**Comment by Drup** [comment]
Hum, is it finished though ? I stopped refactoring because I got stuck, but if it's unstuck, we can factorize quite some more!

**Comment by jonludlam** [comment]
You should still be able to build docs with dune and odig?

**Comment by jonludlam** [comment]
And even unfinished it's certainly nicer to build new CLI commands on, so I'd like to merge this sooner rather than later, even if we do some more refactoring later on.

**Comment by Drup** [comment]
Fair enough :)

**Pull request merged**
