### PR TITLE
Preformatted elements fallback to UA monospace

### PR DESCRIPTION
**Pull request by toastal**
Courier looks mighty ugly on a lot of systems. When in doubt, it’s better to just trust the user agent. This also allow users to set their own preferred option—which is better than a bad option.

### CODE REVIEW

**Review by Julow — APPROVED** [review]
Looks good to me :)

**Comment by Julow** [comment]
You need to update some generated files with `dune runtest --auto-promote`.

**Comment by Julow** [comment]
I've rebased and updated the support files by pushing directly to your branch.
This is ready to be merged.

**Comment by jonludlam** [comment]
Sorry, it needs another rebase following the search merge.

**Comment by Julow** [comment]
Rebased!

**Comment by jonludlam** [comment]
Thanks @toastal!

**Pull request merged**
