### PR TITLE
OCaml 4.11 support

### PR DESCRIPTION
**Pull request by kit-ty-kate**
OCaml 4.11.0~alpha1 is out. This PR fixes the compilation issues with this new version

### CODE REVIEW

**Comment by jonludlam** [comment]
Thanks @kit-ty-kate - looks like the 4.11 build env is broken though?

**Comment by kit-ty-kate** [comment]
oops my bad. Fixed.

**Comment by kit-ty-kate** [comment]
All green

**Comment by jonludlam** [comment]
Thanks!

**Pull request merged**
