### PR TITLE
Less gaps in css

### PR DESCRIPTION
**Pull request by EmileTrotignon**
Reduces gaps in css.

Answers issue #1111.

### CODE REVIEW

**Comment by EmileTrotignon** [comment]
Here is a screenshot of an example page : 
image

**Review by panglesd — COMMENTED** [review]
We don't really need less gaps in CSS, we need to remove the gap introduced in #999 by the introduction of the grid system, which disabled [margin collapse](https://www.joshwcomeau.com/css/rules-of-margin-collapse/):

> the margins of adjacent grid items do not collapse

(From https://www.w3.org/TR/css-grid-1/#item-margins)

The solution you propose changes many margins/paddings (making the result slightly not spaced enough in my opinion, but that's maybe just habits of the previous style) ~~while not solving the original problem~~! Edit: it does solve it by always having the top margin equal to zero... I don't think that having all elements have a 0 value for margin-top is a valid assumption to make!

We can solve the problem either by going away from the grid system, or modifying the html layout: grouping `odoc-preamble` and `odoc-content` in a single element.
I would prefer the second option. It would not affect ocaml.org since they are using the `--as-json` option which would be unaffected by this change. However, we should be careful to check if the layout change affects `odig` stylesheet.

**Comment by EmileTrotignon** [comment]
Oh ok, I did not know about margin collapse, I just git blame on the line that set the topmost margin and found it was quite old, so I thought this was not introduced recently.

I am a bit anxious about changing the order of elements, but I certainly do not want to drop grid.
Another way to do would be to have a rule like :
```css
.odoc-content:first-child {
  margin-top:0 !important;
}
```

**Comment by EmileTrotignon** [comment]
I am also not i agree that assuming every element not to have a top-margin is a bad idea, it seems quite reasonable to me, its a convention that works well, and if a margin-top slips in its a very easy patch to remove it.

**Pull request closed without merging**
