### PR TITLE
Better docs

### PR DESCRIPTION
**Pull request by jonludlam**
Preview here: https://jonludlam.github.io/odoc/

### CODE REVIEW

**Comment by asavahista** [comment]
i wonder if the navigation links at the top of the main section would be helpful on the sidebar as well? or at least a link for home/top and/or up i guess

also a sitemap - or links to more (ideally almost all) pages at the intro page - it's currently less than one page anyway so i don't think it would hurt (i feel like this would be useful as some links are only (?) discoverable through links named e.g. "separate page")

anyway, i've found a few potential (syntax) issues in my first pass:
- in general:
  - some codeblocks ([example](https://github.com/jonludlam/odoc/blob/59e7f7015336817da5fd593077fbcafccc680ac5/doc/dune_wrapping.mld#L30-L31)) are being detected as ReasonML for some reason - which is making the comments not parse properly. if the docs no longer contain Reason i think it can be removed - the other fix would be adding the css class `lang-ocaml` to every code block that's highlighted. if it isn't already, you could also add `lang-plaintext` to all codeblocks that aren't supposed to be highlighted
  - to put it bluntly, particularly terrible contrast ([example](https://jonludlam.github.io/odoc/features.html#hiding)) - this is a css problem, so it's more of a heads up than an actual issue that should be fixed in *this* PR. the blue has contrast ratio 1.74:1; the red has contrast ratio 1.79:1, both of which fail all recommended [web contrast guidelines](https://webaim.org/resources/contrastchecker/)
- `contributing.mld`:
  - [path (to the css) not being formatted as inline code](https://github.com/jonludlam/odoc/blob/59e7f7015336817da5fd593077fbcafccc680ac5/doc/contributing.mld#L11)
  - [`{:` missing `:`](https://github.com/jonludlam/odoc/blob/59e7f7015336817da5fd593077fbcafccc680ac5/doc/contributing.mld#L210)
  - markdown-style code backticks: [1](https://github.com/jonludlam/odoc/blob/59e7f7015336817da5fd593077fbcafccc680ac5/doc/contributing.mld#L86) [2](https://github.com/jonludlam/odoc/blob/59e7f7015336817da5fd593077fbcafccc680ac5/doc/contributing.mld#L128) [3](https://github.com/jonludlam/odoc/blob/59e7f7015336817da5fd593077fbcafccc680ac5/doc/contributing.mld#L142) [4](https://github.com/jonludlam/odoc/blob/59e7f7015336817da5fd593077fbcafccc680ac5/doc/contributing.mld#L187) (grep would work for finding them of course)
- `driver.mld`:
  - [`docs.ocaml.org` not a link](https://github.com/jonludlam/odoc/blob/59e7f7015336817da5fd593077fbcafccc680ac5/doc/driver.mld#L8) - but it's fine for now i think since it's not up yet
  - [stray `...}`](https://github.com/jonludlam/odoc/blob/59e7f7015336817da5fd593077fbcafccc680ac5/doc/driver.mld#L34) - if it's meant to indicate it's unfinished the previous dot point should probably be closed first
  - html comments missing `{%html:` (because they were generated from the `.md`): [1](https://github.com/jonludlam/odoc/blob/59e7f7015336817da5fd593077fbcafccc680ac5/doc/driver.mld#L40) [2](https://github.com/jonludlam/odoc/blob/59e7f7015336817da5fd593077fbcafccc680ac5/doc/driver.mld#L47) [3](https://github.com/jonludlam/odoc/blob/59e7f7015336817da5fd593077fbcafccc680ac5/doc/driver.mld#L54)
- `ocamldoc_differences.mld`:
  - `mld` instead of `.mld`: [1](https://github.com/jonludlam/odoc/blob/59e7f7015336817da5fd593077fbcafccc680ac5/doc/ocamldoc_differences.mld#L17) [2](https://github.com/jonludlam/odoc/blob/59e7f7015336817da5fd593077fbcafccc680ac5/doc/ocamldoc_differences.mld#L56)
- `features.mld`:
  - weird capitalization (admittedly, a huge nitpick): [1](https://github.com/jonludlam/odoc/blob/59e7f7015336817da5fd593077fbcafccc680ac5/doc/features.mld#L5) [2](https://github.com/jonludlam/odoc/blob/59e7f7015336817da5fd593077fbcafccc680ac5/doc/features.mld#L6)
  - [`Paths_types` not formatted as code](https://github.com/jonludlam/odoc/blob/59e7f7015336817da5fd593077fbcafccc680ac5/doc/features.mld#L42)
  -  rename ["separate page"](https://github.com/jonludlam/odoc/blob/59e7f7015336817da5fd593077fbcafccc680ac5/doc/features.mld#L36) to instead explicitly say something like "Please see the page on Dune's library wrapping for more details."?

**Comment by asavahista** [comment]
i haven't checked everything yet - but i'm thinking of editing the post above (with a changelog) rather than making a new post when (well... if) i do, if that's fine of course

**Comment by jonludlam** [comment]
@asavahista This is excellent, thank you very much!

**Comment by asavahista** [comment]
side note: i believe this would close #573 (or otherwise partially invalidate it)?
if it doesn't completely close it i still believe a new issue with a checklist could/should be made (or even better, a project)

**Comment by asavahista** [comment]
it would probably help if gh-pages was rebuilt, there have been a considerable number of commits since last build

**Comment by jonludlam** [comment]
I've done a small update following @asavahista's suggestions - more are to come though. Updated http://jonludlam.github.io/odoc with the current state.

## General issues
- clarification required: in "move all documentation pages to a subdirectory" comment, does this mean source mld files or output html files?
- codeblocks detected as ReasonML: To a large extent this is simply a problem with odoc syntax, there's no way (currently) to specify the language. This is being addressed (https://github.com/ocaml-doc/odoc-parser/pull/2) but won't be fixed for odoc 2.0. In general I'm happy for the odoc website to be 'warts and all' for now so I don't want to post-process the output.

- The suggestions about the dune pages bring up an interesting point: we could of course have more of a hierarchy with `/dune/index.html` `dune/wrapping.html` and so on, but doing so would complicate the driver marginally, and as the driver is intended to be a very simple script that explains how to use odoc I'm wary of adding too much to it. I think for now we'll keep the simple structure and just merge the two dune-specific pages together.

## Specific pages:

- contributing.mld
  + fixed all identified issues
- driver.mld
  + docs.ocaml.org links replaced with v3.ocaml.org (and in parent_child_spec.mld)
  + ... clarified
  + HTML comments - these are mdx-specific, don't need them in the mld file.
- ocamldoc_differences.mld 
  + `mld` replaced with `.mld`
- features.mld
  + fixed capitalisation
  + fixed Paths_types rendering
  + separate page link renamed
  + wide comment shortened
- parent_child_spec.mld
  + `mld` -> `.mld`, `[odoc]` to `[.odoc]` and `[odocl]` -> `[.odocl]` (where appropriate) - also changed indefinite articles! (an `[mld]` file -> a `[.mld]` file :-) )
  + replaced `{[ ... ]}` with `{v ... v}` for non-OCaml code blocks
  + section names capitalised
  + `\(` replaced with `(`
- odoc_for_authors.mld
  + Suggestion to use multiple files rather than 4-level headings inserted
  + TOC acronym expanded
  + added link to `ocamldoc_differences.mld`
  + simple examples added to drivers part at the top
- using_dune.mld and dune_wrapping.mld
  + merged

**Comment by asavahista** [comment]
clarification: the source mld files - generally nobody will need to browse the build output
re: merging the dune files together - i think that's fine

side note: ci is producing some weird failures, not sure if that's a concern

**Comment by asavahista** [comment]
ok so... i don't think i'll be able to comment on the actual content (e.g. whether it's sufficient/comprehensive enough) before i actually need to use it

(apologies in advance if this post is a bit messy. as with the previous post i tend to jump around when making the list)

(of course, feel free to ignore any of the nitpicks in the following list, they are mostly nitpicks after all!)

<details>
<summary>some offtopic stuff</summary>
one thing i've been thinking about re: contributing - i feel like a <a href="https://marketplace.visualstudio.com/items?itemName=vsls-contrib.codetour">code tour</a> (note: currently vs code only) style guide to the codebase would be pretty sweet (and very, <i>very</i> helpful for figuring out where to start debugging an issue/implementing a feature request). it <i>would</i> be quite difficult to get right, but potentially worth the effort.
</details>

- general
  - low priority but just mentioning again that adding links to most/all pages from the index page may be nice
  - Dune, Esy, Opam, Odig, Voodoo, jq, tidy - *not* an issue. just noting that formatting of cli tool names is a *bit* inconsistent (vs `odoc`, `ocamldoc`, `diff` etc.)
- `contributing.mld`
  - other paths should probably be code spans too: [1](https://github.com/jonludlam/odoc/blob/4fbaa0c12bc0d5c930ea089b1cbd76947e609312/doc/contributing.mld#L15) [2](https://github.com/jonludlam/odoc/blob/4fbaa0c12bc0d5c930ea089b1cbd76947e609312/doc/contributing.mld#L82) [3](https://github.com/jonludlam/odoc/blob/4fbaa0c12bc0d5c930ea089b1cbd76947e609312/doc/contributing.mld#L92)
    - [4](https://github.com/jonludlam/odoc/blob/4fbaa0c12bc0d5c930ea089b1cbd76947e609312/doc/contributing.mld#L216-L247)? (library name formatting should probably be consistent with the default formatting, which seems to be code spans)
  - [dune doesn't capitalize "cram"](https://dune.readthedocs.io/en/stable/tests.html) (in "cram tests") so the docs probably shouldn't either. of course this isn't a big deal - to be fair dune/jane street itself seems pretty inconsistent with the capitalization of these. i guess it's mostly just personal preference on my part, since names of CLI programs are normally in lowercase
    - similar with Expect-tests
  - [another possible capitalization issue](https://github.com/jonludlam/odoc/blob/4fbaa0c12bc0d5c930ea089b1cbd76947e609312/doc/contributing.mld#L55)? (linking to header without alt text like last time
  - [developer mode](https://github.com/jonludlam/odoc/blob/4fbaa0c12bc0d5c930ea089b1cbd76947e609312/doc/contributing.mld#L12-L13) -> "[developer](https://developer.mozilla.org/en-US/docs/Tools) [tools](https://developer.chrome.com/docs/devtools/)"
  - (semantic) might want to mention that the shortcut to open this is ctrl + shift + i on most (all?) browsers
  - more accidental markdown formatting? ([`_don't_`](https://github.com/jonludlam/odoc/blob/4fbaa0c12bc0d5c930ea089b1cbd76947e609312/doc/contributing.mld#L95))
  - [`diff`](https://github.com/jonludlam/odoc/blob/4fbaa0c12bc0d5c930ea089b1cbd76947e609312/doc/contributing.mld#L96) vs [diff](https://github.com/jonludlam/odoc/blob/4fbaa0c12bc0d5c930ea089b1cbd76947e609312/doc/contributing.mld#L128) vs [diff](https://github.com/jonludlam/odoc/blob/4fbaa0c12bc0d5c930ea089b1cbd76947e609312/doc/contributing.mld#L172). either way is fine tbh
  - [odoc](https://github.com/jonludlam/odoc/blob/4fbaa0c12bc0d5c930ea089b1cbd76947e609312/doc/contributing.mld#L69) -> `odoc`
  - section link [Testing](https://github.com/jonludlam/odoc/blob/4fbaa0c12bc0d5c930ea089b1cbd76947e609312/doc/contributing.mld#L55) -> testing
  - (semantic) the wording is a bit odd in some places:
    - "the string that the code emitted" -> "the output of the code", or more simply just "the output"?
    - "human developer" - similarly :thinking:, i think "developer" means basically the same thing. *especially* given that this is contributing.mld
    - ["tested by our CI tests"](https://github.com/jonludlam/odoc/blob/4fbaa0c12bc0d5c930ea089b1cbd76947e609312/doc/contributing.mld#L197) - just "CI" instead of "CI tests" should be fine. but also it's the line right before the section on CI so maybe it's unnecessary. even if it's not completely removed i think it can be changed to, say, "we run coverage analysis in our CI pipeline (see below for more details)"
- `driver.mld`
  - more file extensions missing formatting? [1](https://github.com/jonludlam/odoc/blob/4fbaa0c12bc0d5c930ea089b1cbd76947e609312/doc/driver.mld#L37) [2](https://github.com/jonludlam/odoc/blob/4fbaa0c12bc0d5c930ea089b1cbd76947e609312/doc/driver.mld#L60) [3](https://github.com/jonludlam/odoc/blob/4fbaa0c12bc0d5c930ea089b1cbd76947e609312/doc/driver.mld#L69) [4](https://github.com/jonludlam/odoc/blob/4fbaa0c12bc0d5c930ea089b1cbd76947e609312/doc/driver.mld#L325) - might be worth doing a `grep -r mld` (etc.) for those?
  - `<!-- $MDX skip -->` [still there](https://github.com/jonludlam/odoc/blob/4fbaa0c12bc0d5c930ea089b1cbd76947e609312/doc/driver.mld#L40-L54)
  - [Odoc](https://github.com/jonludlam/odoc/blob/4fbaa0c12bc0d5c930ea089b1cbd76947e609312/doc/driver.mld#L24), [odoc not `odoc` (also voodoo)](https://github.com/jonludlam/odoc/blob/4fbaa0c12bc0d5c930ea089b1cbd76947e609312/doc/driver.mld#L3-L7). also mdx -> MDX? and html -> HTML in that region
  - [path/to/x.html -> `path/to/x.html`](https://github.com/jonludlam/odoc/blob/4fbaa0c12bc0d5c930ea089b1cbd76947e609312/doc/driver.mld#L25-L34)
  - quite a number of code blocks have scrollbars for me. not really an issue, considering a lot of them are also very tall, just a heads up. can't (or shouldn't) really do anything about the shell ones, of course
- `odoc_for_authors.mld` - [`(** `](https://github.com/jonludlam/odoc/blob/4fbaa0c12bc0d5c930ea089b1cbd76947e609312/doc/odoc_for_authors.mld#L66) - probably an unintended space. seems like the space after it being missing is a HTML quirk
  - [Preamble](https://github.com/jonludlam/odoc/blob/4fbaa0c12bc0d5c930ea089b1cbd76947e609312/doc/odoc_for_authors.mld#L185) -> preamble 
  - (semantic) more odd wording (?):
    - ["structurally placed in the HTML"](https://github.com/jonludlam/odoc/blob/4fbaa0c12bc0d5c930ea089b1cbd76947e609312/doc/odoc_for_authors.mld#L57-L58) -  specifically, the word "structurally". "[placed/located] immediately after the preamble in the HTML" is an option, removing just the "structurally" is fine too

**Comment by jonludlam** [comment]
I believe I have made most of the updates suggested - many thanks to everyone who helped with this! I'll merge this now so we have something we can release, and we can continue updating and improving it in further PRs.

**Pull request merged**
