### PR TITLE
Resolve definition point comments in the context of any expansion

### LINKED ISSUE #713: Unqualified preamble references are not resolved when the preamble is outside the module.
In the following module the reference to type {!t} is resolved in the second case but not in the first case.

```ocaml
(** The module M. 

    Resolve type {!t}. *)
module M : sig 

  type t
end
```

```ocaml
module M : sig 
(** The module M. 

    Resolve type {!t}. *)

  type t
end
```

This seems to be a regression since I suddenly have quite a bunch of unresolved xrefs in my module preambles (example in astring [here](https://b0-system.github.io/odig/doc/astring/Astring/String/index.html), [src](https://github.com/dbuenzli/astring/blob/ec7a266a3a680e5d246689855c639da53d713428/src/astring.mli#L176-L187)).

### PR DESCRIPTION
**Pull request by jonludlam**
Fixes #713 

I tested this on the deps of odoc and found changes in `Astring.String` and `Cmdliner.{Arg, Manpage, Term}`, which looked correct. However, I also found changes in tyxml that were not so obviously right - e.g. in `Html_sigs`. Compare these:

https://jonludlam.github.io/odoc/deps/tyxml/Html_sigs/module-type-T/Xml/index.html
https://ocsigen.org/tyxml/4.4.0/api/Html_sigs.T.Xml

In both of these the links from `elt` and `attrib` go to the parent page, which looks correct to me. With this change, that comment is now resolved in the context of the module `Xml` and therefore they both link to the definitions of `elt` and `attrib` in that page instead of the parent. This looks incorrect to me (neither has a type variable!)

### CODE REVIEW

**Comment by jonludlam** [comment]
N.b. in the underlying source the references `elt` and `attrib` are both unqualified: https://github.com/ocsigen/tyxml/blob/master/lib/html_sigs.mli#L83

**Comment by jonludlam** [comment]
The differences I've noted so far have been both good and bad. Given that a) the implementation is a bit unpleasant - mainly because b) it's quite different from how reference resolution works elsewhere, and c) this behaviour is a bit surprising, I want to double check that it's actually a good idea to do this. The original argument was that it broke things that previously worked -- and that _is_ a reasonable argument -- but it also broke things that were working correctly _before_ this change. Admittedly my package sample size is small, so I can't say whether this patch does more harm than good overall. 

One possibility: I note that for @dbuenzli's affected libraries, the comment is written just above the explicit signature of the module: e.g. in [astring](https://github.com/dbuenzli/astring/blob/master/src/astring.mli#L176-L187) and in [cmdliner](https://github.com/dbuenzli/cmdliner/blob/master/src/cmdliner.mli#L29-L41), whereas for tyxml the [module type is just a path](https://github.com/ocsigen/tyxml/blob/master/lib/html_sigs.mli#L83-L93).

I think the behaviour in this PR is considerably less surprising for @dbuenzli's case than for tyxml's case (though still _slightly_ odd). As a compromise we could switch to the new behaviour only on existence of an explicit signature like in Astring and Cmdliner. It's still relatively easy to explain the behaviour and I suspect the code change in odoc could be less invasive.

The other solution is to do nothing, but change the source. For Astring and Cmdliner I think that amounts to putting that comment within the signature of the modules rather than just above it. Of course, this does mean that previous versions would remain broken.

@dbuenzli, @Drup, @lpw25 - opinions?

**Comment by dbuenzli** [comment]
> The other solution is to do nothing, but change the source. For Astring and Cmdliner I think that amounts to putting that comment within the signature of the modules rather than just above it

You can also keep it above and simply qualify the identifiers with the module (which I already did in some libraries I had to release). My only gripes with all that is that it somehow kills the whole behaviour we defined for module preambles which was the idea that the following where somehow fully equivalent:

 ```ocaml
(** This module bla … *)
module B : sig 
end
```
and 
```ocaml
module B : sig 
(** This module bla … *)
end
```

But I don't think explaining to people that in the first case your are outside of the module so you need to qualify is *that horrible* – it's not absurd for an OCaml programmer.

I don't have a good grasp of the problems involved. Personally I don't see it as a big deal to change my sources in the future, as long as the actual scoping rules are finally nailed down and made known. See #332, #42, #594.

**Comment by jonludlam** [comment]
OK, I think on balance the scoping rules make more sense to me as they currently are rather than with this PR merged. Let's go the route of changing the source instead.

**Pull request closed without merging**
