### PR TITLE
Fix record fields and constructors indentation

### PR DESCRIPTION
**Pull request by lubegasimon**
Addressing #505.

Screenshot_2020-10-16 Renderer (odoc Odoc_document Renderer)(1)

### CODE REVIEW

**Comment by Drup** [comment]
The indentation fix is great :+1: . I'll merge as soon as you drop the linkification change (as we discussed in #506 ).

**Comment by Drup** [comment]
Also, as a small aside: if we decide to remove pieces of markup, I prefer if to actually remove them, instead of just turning them invisible. ;)

**Comment by lubegasimon** [comment]
> Also, as a small aside: if we decide to remove pieces of markup, I prefer to actually remove them, instead of just turning them invisible. ;)

You're right, for performance reasons.

**Comment by Drup** [comment]
> You're right, for performance reasons.

Actually, no: for software engineering reason: code that is used to produce unneeded stuff is dead, and dead code is technical debt, which leads to unmaintainable messy software.

**Review by Drup — APPROVED** [review]

**Pull request merged**
