### PR TITLE
Remove impossible cases in the HTML generator (links within links)

### PR DESCRIPTION
**Pull request by favonia**
Nested links are impossible and the relevant code should be removed.

### CODE REVIEW

**Comment by dbuenzli** [comment]
Could you please provide an example of what this changes (`ocamldoc` and corresponding `html` markup). Changing the markup is never innocuous for stylesheets.

**Comment by dbuenzli** [comment]
Could you please provide an example of what this changes (`ocamldoc` and corresponding `html` markup). Changing the markup is never innocuous for stylesheets.

**Comment by favonia** [comment]
@dbuenzli I missed the following code that would replace nested links with `` `Emphasis``. So, it seems there's no way to trigger this. So, this PR is at most a tiny style clean-up. What should I do in this case?

https://github.com/ocaml/odoc/blob/b7a98282f055198a96ee1976ff939f058d6aa881/src/model/semantics.ml#L176-L185

**Comment by dbuenzli** [comment]
> So, it seems there's no way to trigger the function; this PR is at most a tiny style clean-up. What should I do in this case?

`assert false`

**Comment by favonia** [comment]
Done.

**Comment by favonia** [comment]
Any plan to merge this PR?

**Comment by jonludlam** [comment]
Sorry for the delay in this, I've rebased and will merge there.

**Pull request closed without merging**
