### PR TITLE
Render TOC in nested pages

### PR DESCRIPTION
**Pull request by rizo**
Currently the table of contents is only rendered for top-level modules. This PR implements the rendering for all nested items (modules, module types, classes, functors and functor parameters) and makes some other minor adjustments.

### Full list of changes

* Render TOC (if not empty) inside header in all nested pages.
* Fix a bug where functor arguments were listed in reverse order ([diff](https://github.com/ocaml/odoc/compare/master...rizo:render-nested-toc?expand=1#diff-46e526e8d708dd25c7f790e20662ad2eR1371)).
* Remove the `doc` CSS class from class items, to be consistent with other nested items ([diff](https://github.com/ocaml/odoc/compare/master...rizo:render-nested-toc?expand=1#diff-46e526e8d708dd25c7f790e20662ad2eL1171)).
* Render functor parameters as `ul` (and not as a `dl`).
* Extend the "nested" HTML test to cover the proposed changes.
  * The TOC rendering for nested pages is not currently tested because of https://github.com/ocaml/odoc/issues/213.

### CODE REVIEW

**Comment by aantron** [comment]
I suggest...

- Addressing #213 first.
- Splitting up the one commit into the individual changes that were made, so each can be reviewed trivially. Note that links to code diffs don't also link to diffs in the test cases, and the net effect of combining everything is to partially defeat the advantage to review offered by having expected output committed to the repo.

I can take care of #213, but please let me know if you have intent to do it.

**Comment by rizo** [comment]
Thanks for the suggestions and apologies for bundling everything (the changes seemed rather small). I changed the history to reflect the individual changes accordingly.

> Addressing #213 first.

There's a large number of other nested files (40+) the are not currently tested. Although I agree that #213 must to be fixed, I don't see why this PR should be blocked until then. I can add the generated nested expect files if that helps for now.

I'm currently working on other PRs, so feel free to work on #213.

**Comment by rizo** [comment]
It is possible to test this now! I'll add the generated files later today.

**Comment by rizo** [comment]
@aantron I think this can be merged now, unless you have any objections/suggestions.

**Comment by rizo** [comment]
Thanks, @dbuenzli.

I think @aantron had some potential suggestions with regards to testing in this PR. @aantron, if that's the case, please let me know and I'll work on that separately.

**Comment by aantron** [comment]
Yes. If the changes are trivial, I'll just make them.

**Pull request merged**
