### PR TITLE
WIP: improve the navigation menu

### PR DESCRIPTION
**Pull request by gpetiot**
This is WIP, inspired by #127 and #479

So far, the data is extracted from the .odoc file (without links), but it can surely be improved.

### CODE REVIEW

**Comment by dbuenzli** [comment]
I doubt it's possible to see what you are trying to do through html diffs – and thus assess whether this is an *improvement*. Would you mind coming up with a description or a design mockup of what you do and show us how it fares on a non-trivial selection of packages ?

**Comment by gpetiot** [comment]
Not definitive but the design I'm going for is something akin to https://hexdocs.pm/phoenix/Phoenix.html, with a tab to navigate through the contents of the page, and a tab to navigate through the definitions.

**Comment by dbuenzli** [comment]
I see thanks.

Note that `ocaml.org` also seems to be working on similar functionality, could we maybe establish a common ground ?

In particular I think it's nice if standalone `odoc` docsets are not necessarily one-to-one but at least give a good idea on how your docs are going to show up on `ocaml.org` since the navigation in presence does influences the way you design your docs.

**Comment by tmattio** [comment]
> Note that ocaml.org also seems to be working on similar functionality, could we maybe establish a common ground ?
> 
> In particular I think it's nice if standalone odoc docsets are not necessarily one-to-one but at least give a good idea on how your docs are going to show up on ocaml.org since the navigation in presence does influences the way you design your docs.

Absolutely!

At the moment ocaml.org uses a custom design for the odoc-generated documentation, but a medium-term goal is to re-use what odoc generates (or at least be as close as possible). When odoc generates a sidebar with a global navigation, I think we can start exploring how to converge.

Inversely, it would be interesting to use the learnings we've had on ocaml.org to discuss the design of the navigation in odoc.
In particular, @sabine spent significant time iterating on the design, interviewing users, etc. and will certainly be able to share insights on the UX that are relevant to the current PR.

**Comment by sabine** [comment]
Adding to @tmattio's explanation: We do currently have a UX/UI designer working on improving the navigation on ocaml.org and, in particular improving the package documentation navigation, so yes, I totally agree, converging on something that can be upstreamed would be a major goal.

**Comment by gpetiot** [comment]
Closing this PR because it needs (if ever) to be restarted with a clear plan in mind.

**Pull request closed without merging**
