### PR TITLE
Remove the prefix when rendering a label reference

### PR DESCRIPTION
**Pull request by jonludlam**
Fixes ocaml/v3.ocaml.org-server#83

### CODE REVIEW

**Review by Julow — COMMENTED** [review]
Some tests need to be promoted. Otherwise, looks good :)

**Comment by jonludlam** [comment]
Thanks!

**Comment by gadmm** [comment]
Just got a notification for this. IIUC in the original example this would give "global_memory_limits let you bound..." instead of "Global memory limits let you bound...", right? In the original version, the string is taken from the section title being pointed to.

**Comment by jonludlam** [comment]
Ah, you're right! I entirely missed this feature! Hrm, this will be a bit more work.

**Comment by gadmm** [comment]
Thanks for looking into it (an alternative which is entirely fine to me would be to be able to define the text of the link, like you can already do for external links).

**Comment by jonludlam** [comment]
You should already be able to do this: `{{!section:Memprof_limits.global_memory_limits}Global memory limits}` or, using the better syntax, `{{!Memprof_limits.section-global_memory_limits}Global memory limits}`

**Comment by jonludlam** [comment]
But I'd like to fix this issue anyway as it's a regression from 1.5!

**Comment by gadmm** [comment]
I'm pretty sure I already tried something like this, I'll try again.

**Pull request merged**
