### PR TITLE
Style: Remove font fallback to Helvetica, Arial

### PR DESCRIPTION
**Pull request by Julow**
These fonts are not common nowadays and do not look native.

Let the user agent set the fallback font in the rare cases the distributed font cannot be used (eg. missing on server or unsupported by client).

### CODE REVIEW

**Comment by jonludlam** [comment]
This needs rebasing.

**Comment by Julow** [comment]
I suggest that I rebase after https://github.com/ocaml/odoc/pull/967 is merged.

**Comment by jonludlam** [comment]
Ah! I hadn't spotted that you'd just done that. Let's get that one in, yes.

**Comment by Julow** [comment]
Rebased.

**Pull request merged**
