### PR TITLE
Upgrade OCamlformat to 0.26.1

### PR DESCRIPTION
**Pull request by Julow**
The aim of this preview is to gather feedback.

This is a bug-fix release and is compatible with the slightly changed let-binding syntax in OCaml 5.1.
Changelog can be found here: https://github.com/ocaml-ppx/ocamlformat/blob/main/CHANGES.md

### CODE REVIEW

**Review by trefis — APPROVED** [review]
LGTM.

**Comment by Julow** [comment]
Not too fast, it's not released yet :)

**Comment by trefis** [comment]
Don't worry, I wasn't going to merge :)

**Comment by Julow** [comment]
OCamlformat has been released 1 week ago, this is ready for merging.

**Comment by EmileTrotignon** [comment]
Lets make the CI green again and merge

**Comment by Julow** [comment]
I'll rebase and merge this once all the PRs for 2.4 are merged.

**Pull request merged**
