### PR TITLE
Add changes to opam files from opam-repository tests

### PR DESCRIPTION
**Pull request by jonludlam**
So we don't forget them again!

### CODE REVIEW

**Comment by lubegasimon** [comment]
> So we don't forget them again!

A kind request to clarify a little more 🙂!

**Comment by jonludlam** [comment]
Sure, check these: https://github.com/ocaml/opam-repository/commits/master/packages/odoc/odoc.2.0.0/opam

**Comment by lubegasimon** [comment]
> Sure, check these: https://github.com/ocaml/opam-repository/commits/master/packages/odoc/odoc.2.0.0/opam

That’s helpful, thanks!

**Comment by jonludlam** [comment]
Also here: https://opam.ci.ocaml.org/github/ocaml/opam-repository/commit/238c2d046549252b37ca3b89a6addc058f696982 -- these are the logs of the failures fixed by these changes.

**Pull request merged**
