### PR TITLE
Compatibility with OCaml 5.3

### PR DESCRIPTION
**Pull request by Julow**
This fixes the compatibility then update the Opam constraints.

### CODE REVIEW

**Comment by Julow** [comment]
This is intended to be released on the 2.4 branch so I'll take care of the changelog later.

**Comment by jonludlam** [comment]
Tests are failing on 4.04 and 4.06.

**Comment by Julow** [comment]
This seems to be an issue in the parser. I found a workaround.

**Comment by Julow** [comment]
CI is green, let's merge and cut a release !

**Pull request merged**
