### PR TITLE
The right command to generate doc

### PR DESCRIPTION
**Pull request by cnmade**
is `dune build @doc`

see reference: https://dune.readthedocs.io/en/stable/documentation.html#building-documentation

### CODE REVIEW

**Review by Julow — COMMENTED** [review]
`@docgen` builds Odoc's doc with [this Mdx document](https://github.com/ocaml/odoc/blob/master/doc/driver.md?plain=1) as an example of how to drive Odoc.

I don't know what is best between `@docgen` or `@doc` but:
- The path in which to find the docs corresponds to `@docgen` (even thought it's wrong, should be `_build/default/doc/html/odoc/index.html`)
- The Mdx dependency of `@docgen` is not installed by the script

**Comment by cnmade** [comment]
The default install won't use mdx i think. i tried many times, it default generate html , which @doc does.

**Comment by jonludlam** [comment]
I just tested the instructions and it worked for me. `mdx` ought to get installed when you specify `-t` on the `opam install` line - does that not work for you?

**Comment by cnmade** [comment]
image
I used the way .

I am not reading the readme.md first.

but , for user side, why this document not the same behaviour with dune document, very straige.

**Comment by jonludlam** [comment]
OK, since you're not using the README but this PR changes it, let's close this one.

**Pull request closed without merging**
