### PR TITLE
Compatibility with 4.02

### PR DESCRIPTION
**Pull request by Julow**

### CODE REVIEW

**Comment by panglesd** [comment]
How much do we want to maintain compatibility with older versions, now that `ocaml-ci` does check only on `4.14` and `5.1`?

`odoc` is only used to build the doc, dropping compatibility shouldn't completely break build of a package.

I think that without "full CI coverage" of supported versions, it will be very hard to maintain full compatibility.

**Comment by Julow** [comment]
I'm in favor of dropping compatibility with OCaml `< 4.14` but that wasn't planned for this release and is not an option for now.

You are right that we need full coverage as almost every versions occur in `enabled_if` dune fields and in cppo conditions.
To limit the waste of power, I included every pair versions. Do you think that's a good idea ?

**Comment by panglesd** [comment]
> Do you think that's a good idea ?

That's fine to me! I only remember compatibility issues on ranges of versions of length at least two.

**Review by panglesd — APPROVED** [review]
CI is green, let's merge and (hopefully) undo most of it for next release!

**Pull request merged**
