### PR TITLE
Fix HTML rendering of empty variant types

### PR DESCRIPTION
**Pull request by CraigFe**
Resolves https://github.com/ocaml/odoc/issues/416 with the solution suggested there.

### CODE REVIEW

**Comment by CraigFe** [comment]
Namely:
image

**Comment by jonludlam** [comment]
Thanks @CraigFe !

**Comment by CraigFe** [comment]
Aha, the tests fail because of empty variant types not being available pre-4.07.

Is there an existing way to restrict tests to a subset of compiler versions? (I can't find one.)

**Comment by aantron** [comment]
@CraigFe only this:

https://github.com/ocaml/odoc/blob/738f4e5405ef11d2442ddd40b9d6f07db46e14c4/test/html/test.ml#L288-L303

**Comment by jonludlam** [comment]
only a rather heavy-handed one - stick it in `recent.mli`, which is only used in 4.08 and above. We could do with a better way to handle these sorts of things.

**Comment by CraigFe** [comment]
Done :slightly_smiling_face:

**Pull request merged**
