### PR TITLE
fix and update CONTRIBUTING.md

### PR DESCRIPTION
**Pull request by asavahista**
basically a draft - there is still a lot that potentially needs to be changed.
for example the roadmap was last updated 3 years ago (and the link is to the closed roadmap issue - maybe the link could be changed to one of the projects instead).
actually, most of the doc is still 3 years old so it might be worth going over the entire thing to make sure the overview is complete and correct

### CODE REVIEW

**Comment by lubegasimon** [comment]
Thanks for your efforts @asavahista, indeed documentation pull requests are a real deal. Though I’m certainly not sure of how much of this content will be overwritten by https://github.com/ocaml/odoc/pull/733.

**Comment by asavahista** [comment]
ah, indeed it's completely obsoleted by that

**Comment by jonludlam** [comment]
Thanks for the contribution anyway, @asavahista. Just bad timing that it came when we're overhauling lots of docs! Or good timing if you look at it another way: I'm looking for feedback on that docs PR - would you care to take a look over them and see if they look OK?

**Comment by asavahista** [comment]
@jonludlam yeah, actually i've already been looking around a bit - just a heads up though, i'll probably only be looking for (possible) syntactic errors first as those are easier to find than semantic errors

**Comment by jonludlam** [comment]
That'd be great, thank you!

**Pull request closed without merging**
